### ISSUE TITLE
`norman` failure while handling function calls

### ISSUE THREAD

**Issue by arindam-8** [srg-imperial/norman#4]
Following is a standalone testcase, which induces a `norman` failure:

```
int main() {
	int p = 5;
	if(p > 2) {
		printf("Exiting now\n");
		exit(0);
		printf("Shouldn't reach\n");
	} else {
		p = p + 1;
		printf("%d", p);
	}
	return 0;
}
```
`norman` produces the following output:
```
int main() {
	int p;
	p = (5);
	;
	int _IfCond_main_1 = (p > 2);
	if(_IfCond_main_1) {
		pprintf;"Exiting now\n");
		eexit;0);
		printf("Shouldn't reach\n");
	} else {
		p = p + 1;
		printf("%d", p);
	}
	return 0;
}
```
which crashes with the following error message,
```
test.c:19:3: error: use of undeclared identifier 'pprintf'
  pprintf;"Exiting now\n");
  ^
test.c:19:26: error: extraneous ')' before ';'
  pprintf;"Exiting now\n");
                         ^
test.c:20:3: error: use of undeclared identifier 'eexit'
  eexit;0);
  ^
test.c:20:10: error: extraneous ')' before ';'
  eexit;0);
         ^
4 errors generated.
```
Let me know if I might have missed something.

**Comment by danielschemmel** [comment]
It looks like this issue is due to implicitly inserted function declarations for `printf` and `exit`, which cause another weird rewriter issue.

The simple solution is to not try to write out implicit decls, however that to some degree only treats the symptoms of whatever is wroing with the rewriting and reinsertion. Commit 74a0a3c256d938a8723259ba7b8f4490245bc28c is currently in testing for this issue.
